---
resources:
- name: git-pipeline
  type: git
  source:
    uri: https://github.com/ferozjilla/onboarding-pipeline.git

jobs:
- name: empty-box
  plan:
  - get: git-pipeline
    trigger: true
  - task: echo
    file: git-pipeline/tasks/echo.yml

